FROM registry.fedoraproject.org/fedora-minimal:34

RUN microdnf -y install git libpq postgresql python3 && microdnf clean all

RUN pip3 install psycopg psycopg_pool starlette sse_starlette uvicorn

ADD main.py /app/main.py
ADD static /app/static

WORKDIR /app
ENTRYPOINT ["python3", "main.py"]
